---

- name: Mastodon
  hosts: openbsd
  roles:
    - { role: mastodon, tags: ["mastodon"] }
    - { role: redis, tags: ["redis", "mastodon"] }
    - { role: postgresql, tags: ["postgresql", "mastodon"] }
    - { role: nginx, tags: ["nginx", "mastodon"] }
    - { role: acme, tags: ["acme", "mastodon"] }
