---

- name: Install pre-reqs
  tags:
    - system
    - pkgs
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - ImageMagick
    - autoconf-2.69p2
    - automake-1.15.1
    - bwm-ng
    - ffmpeg
    - gcc
    - git
    - gnupg-2.2.3
    - icu4c
    - libidn
    - node
    - protobuf
    - ruby24-addressable
    - ruby24-bundler
    - ruby24-nokogiri
    - ruby24-puma
    - ruby24-sanitize

- name: Make python symlink
  file:
    state: link
    src: /usr/local/bin/python2.7
    dest: /usr/local/bin/python

- name: Configure login.conf
  tags:
    - system
    - login.conf
  copy:
    src: login.conf
    dest: /etc/login.conf
    owner: root
    group: wheel
    mode: 0644

- name: Install "yarn" node.js package globally.
  tags:
    - system
  npm:
    name: yarn
    global: yes

- name: Add _mastodon group
  group:
    name: _mastodon
    state: present

- name: Add _mastodon user
  tags:
    - system
  user:
    name: _mastodon
    shell: /bin/ksh
    home: /var/www/_mastodon
    state: present
    group: _mastodon

- name: Add profile for _mastodon
  copy:
    dest: /var/www/_mastodon/.profile
    owner: _mastodon
    group: daemon
    content: |
            PATH=$HOME/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/games:.
            export PATH HOME TERM
            CC=/usr/bin/clang
            CXX=/usr/bin/clang++
            AUTOCONF_VERSION=2.69
            AUTOMAKE_VERSION=1.15
            RAIL_ENV=production
            NODE_ENV=production
            DB_POOL=5

            alias bundle=/usr/local/bin/bundle24

- name: Create .gitconfig
  copy:
    dest: /var/www/_mastodon/.gitconfig
    owner: _mastodon
    group: daemon
    content: |
            [gpg]
                program = /usr/local/bin/gpg2
            [transfer]
                fsckobjects = true
            [fetch]
                fsckobjects = true

- name: Copy github's gpg pubkey
  tags:
    - code
  copy:
    src: pubkey.asc
    dest: /var/www/_mastodon/pubkey.asc
    owner: _mastodon

- name: Import github's gpg key
  tags:
    - code
  become: true
  become_method: su
  become_user: _mastodon
  command: 'gpg2 --import /var/www/_mastodon/pubkey.asc'
  register: gpg_output
  changed_when: "'imported: 1' in gpg_output.stderr"

- name: Clone mastodon repo
  tags:
    - code
  become: true
  become_method: su
  become_user: _mastodon
  git:
    repo: https://github.com/tootsuite/mastodon.git
    dest: /var/www/_mastodon/live
    verify_commit: true
    version: "{{ mastodon_release | default('master') }}"

- name: Run Bundle
  tags:
    - bundle
    - deps
  become: true
  become_method: su
  become_user: "_mastodon"
  command: "bundle24 install --deployment --without development test"
  args:
    chdir: /var/www/_mastodon/live
    creates: /var/www/_mastodon/live/vendor/bundle/

- name: Run Yarn
  tags:
    - bundle
    - deps
  become: true
  become_method: su
  become_user: "_mastodon"
  command: "yarn install --pure-lockfile"
  args:
    chdir: /var/www/_mastodon/live
  register: yarn
  failed_when: "'OPTIONAL, you can safely ignore this error' not in yarn.stdout"

- name: Create mastodon env.production file
  tags:
    - secrets
    - env
    - rake
  template:
    src: env.production.j2
    dest: /var/www/_mastodon/live/.env.production
    owner: _mastodon
    group: www
    mode: 0640

- name: Copy rake helper script
  copy:
    src: rake_runner.sh
    dest: /var/www/_mastodon/rake_runner.sh
    mode: 0755
    owner: "_mastodon"

- name: Copy tmux start script
  copy:
    src: starter.sh
    dest: /var/www/_mastodon/starter.sh
    mode: 0755
    owner: "_mastodon"

- name: Setup DB
  tags:
    - db
  become: true
  become_method: su
  become_user: "_mastodon"
  shell: "/var/www/_mastodon/rake_runner.sh db"
  args:
    chdir: /var/www/_mastodon/live
    creates: /var/www/_mastodon/db

- name: Setup JS / CSS
  tags:
    - cssjs
  become: true
  become_method: su
  become_user: "_mastodon"
  shell: "/var/www/_mastodon/rake_runner.sh cssjs"
  ignore_errors: True
  args:
    chdir: /var/www/_mastodon/live
    creates: /var/www/_mastodon/cssjs

